### ISSUE TITLE
build_table error

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/synapsePythonClient#943] opened 2022-10-07 18:45 UTC
# Bug Report

*Github issues is reserved for bug report. If you have a question, please don't use this form.
 Instead, please ask your question on the [Synapse Help Forum](https://www.synapse.org/#!SynapseForum:default).*

## Operating system

Ubuntu 

## Client version
2.7.0

## Description of the problem

The synapseClient function build_table returns an error that is unclear on how to fix.

### Expected behavior

A synapse table should have been added based on the dataframe input.

### Actual behavior

*What actually happened? Provide output or error messages from the console, if applicable.*

The tbl is a pandas.dataframe object as a result from a SQL query. 
```
>>> import synapseclient as sc
>>> project = syn.get("syn39024404")
>>> tbl = <result of SQL query>
>>> syn = sc.Synapse()
>>> syn.login()
Welcome, Andrew Lamb!
>>> table = sc.table.build_table("test", project, tbl)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematic-db-jjxvquAh-py3.9/lib/python3.9/site-packages/synapseclient/table.py", line 1601, in build_table
    cols = as_table_columns(values)
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematic-db-jjxvquAh-py3.9/lib/python3.9/site-packages/synapseclient/table.py", line 435, in as_table_columns
    maxStrLen = df[col].str.len().max()
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematic-db-jjxvquAh-py3.9/lib/python3.9/site-packages/pandas/core/generic.py", line 5575, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'str'
```

**Comment by thomasyu888** [comment] 2022-11-03 06:12
Closing for now as this error was caused by duplicated column headers.

**Closed by thomasyu888** 2022-11-03 06:12 UTC
