### ISSUE TITLE
KeyError when trying to download using Synapse Client 1.8.1

### ISSUE THREAD

**Issue by npklein** [Sage-Bionetworks/synapsePythonClient#547] opened 2018-05-23 14:24 UTC
I am trying to download syn3157325 using `files = synapseutils.syncFromSynapse(syn, 'syn3157325', path = 'ROSMAP/')`. I get the error 

```
Traceback (most recent call last):
  File "download_data.py", line 32, in <module>
    files = synapseutils.syncFromSynapse(syn, 'syn3157325', path = 'ROSMAP/')
  File "/apps/software/Python/3.6.3-foss-2015b/lib/python3.6/site-packages/synapseutils/sync.py", line 104, in syncFromSynapse
    generateManifest(syn, allFiles, filename)
  File "/apps/software/Python/3.6.3-foss-2015b/lib/python3.6/site-packages/synapseutils/sync.py", line 116, in generateManifest
    keys, data = _extract_file_entity_metadata(syn, allFiles)
  File "/apps/software/Python/3.6.3-foss-2015b/lib/python3.6/site-packages/synapseutils/sync.py", line 135, in _extract_file_entity_metadata
    row.update(_get_file_entity_provenance_dict(syn, entity))
  File "/apps/software/Python/3.6.3-foss-2015b/lib/python3.6/site-packages/synapseutils/sync.py", line 152, in _get_file_entity_provenance_dict
    'executed' : ';'.join(prov._getExecutedStringList()),
  File "/apps/software/Python/3.6.3-foss-2015b/lib/python3.6/site-packages/synapseclient/activity.py", line 339, in _getExecutedStringList
    return self._getStringList(wasExecuted=True)
  File "/apps/software/Python/3.6.3-foss-2015b/lib/python3.6/site-packages/synapseclient/activity.py", line 329, in _getStringList
    usedList.append(source['name'])
```

printing usedList:

`{'wasExecuted': True, 'concreteType': 'org.sagebionetworks.repo.model.provenance.UsedURL', 'url': 'https://github.com/Sage-Bionetworks/ampAdScripts/blob/master/Broad-Rush/migrateROSMAPGenotypesFeb2015.R'}`

I put a try/except around `usedList.append(source['name'])`, as far as I double check it allowed me to download all the data correctly.

**Comment by kellrott** [comment] 2018-06-07 16:01
Getting similar error:

```
synapse login --remember-me
Synapse username: kellrott
Password for kellrott:

PasswordSetError: Can't store password on keychain
```

**Comment by kimyen** [comment] 2018-06-07 18:51
@npklein , thank you for reporting the error. We are tracking it here: https://sagebionetworks.jira.com/browse/SYNPY-744

**Comment by zimingd** [comment] 2018-06-07 18:59
@kellrott The error you got is a separate issue caused by integration with one of our dependencies, `keyring` . Could you please open a separate GitHub issue and include information about which Operating System you are using , your Python version, and the output of : `import keyring; print(type(keyring.get_keyring()))`?

**Comment by kimyen** [comment] 2018-06-09 01:40
This issue has been fixed on develop branch.

**Closed by kimyen** 2018-06-09 01:40 UTC

**Comment by kellrott** [comment] 2018-06-22 17:51
```
>>> import keyring; print(type(keyring.get_keyring()))
<class 'keyring.backends.OS_X.Keyring'>
```

**Comment by kimyen** [comment] 2018-06-22 19:08
@kellrott , could you kindly open a separate Github issue? Thank you.
